homework 5
makarovNick/made_2019_cpp pull request #2
Opened 2019-11-08 19:41 UTC by makarovNick

пытался реализацию оставить в .cpp файлах как inline . Не помогло. поэтому все в .h. Как надо было правильно?

2019-11-10 15:43 UTC, smirnov-vs requested changes

2019-11-10 15:43 UTC, smirnov-vs commented on 05/Deserializer.h
> +inline Error Deserializer::load(T&& object) const
правильно писать их в классе сразу, они там сразу инлайн
шаблонные функции всегда реализуются там же где объявлены

2019-11-10 15:43 UTC, smirnov-vs commented on 05/Deserializer.h
> +	if (std::is_same<T, bool>::value || std::is_same<T, bool&>::value)
так можно делать только через if constexpr, иначе другая ветка тоже будет проинстанцирована, могут быть проблемы
надо вызывать перегруженные функции для каждого типа

2019-11-11 11:56 UTC, makarovNick commented on 05/Deserializer.h
> +inline Error Deserializer::load(T&& object) const
@smirnov-vs, исправил

2019-11-18 09:03 UTC, smirnov-vs approved these changes
привет!
наверно проглядел письмо, поэтому не проверил еще раз

я зачел

2019-11-18 15:08 UTC, merged