Home task 6
makarovNick/made_2019_cpp pull request #3
Opened 2019-11-16 15:55 UTC by makarovNick

2019-11-18 09:14 UTC, smirnov-vs requested changes
привет!
надо найти и устранить утечки памяти

2019-11-18 09:14 UTC, smirnov-vs commented on 06/BigInt.cpp
> +	, _capacity(std::move(moved._capacity))
мувы примитивных типов

2019-11-18 09:14 UTC, smirnov-vs commented on 06/BigInt.cpp
> +}
неправильно работает

2019-11-18 09:14 UTC, smirnov-vs commented on 06/BigInt.cpp
> +	std::copy(copied.digits, copied.digits + copied._size, digits);
что если не влезет?

2019-11-18 18:52 UTC, makarovNick commented
> привет!
> надо найти и устранить утечки памяти

Нашел обе в operator+ и в operator-. Исправил

2019-11-20 17:32 UTC, smirnov-vs requested changes

2019-11-20 17:32 UTC, smirnov-vs commented on 06/BigInt.cpp
> +		if (_capacity < copied._capacity)
наверно достаточно обеспечить, чтобы `_capacity` было == 0, если указатель nullptr, тогда можно убрать `if (!digits)`

2019-11-20 17:32 UTC, smirnov-vs commented on 06/BigInt.cpp
> +}
не исправлено, нужно сделать верно для зачета

2019-11-20 17:33 UTC, smirnov-vs commented on 06/BigInt.cpp
> +	: digits(std::move(moved.digits))
указатель тоже является примитивным типом, у него нет конструктора перемещения, значит мув лишний

2019-11-24 10:04 UTC, smirnov-vs approved these changes
привет!
все окей, я зачел

2019-11-24 12:30 UTC, merged