Home task 7
makarovNick/made_2019_cpp pull request #4
Opened 2019-11-21 16:48 UTC by makarovNick

Самый очевидный способ.

Есть еще вариант в unnamed namespace завести счетчик индексов и строку для копирования.
И пройтись по всем аргументам, заменяя соответственные {index} .
Не знаю, корректно ли так.

2019-11-24 10:44 UTC, smirnov-vs requested changes

2019-11-24 10:44 UTC, smirnov-vs commented on 07/format.h
> +    while(is >> c)
это неоптимально, достаточно циклом идти по символам входной строки

2019-11-24 14:06 UTC, makarovNick commented on 07/format.h
> +    while(is >> c)
> это неоптимально, достаточно циклом идти по символам входной строки

исправил

2019-12-01 10:18 UTC, smirnov-vs approved these changes
привет!
не видел твоего письма, что исправления готовы, может пропустил

я зачел

2019-12-01 11:28 UTC, merged