Home task 8
makarovNick/made_2019_cpp pull request #5
Opened 2019-11-28 20:20 UTC by makarovNick

Мне показалось, что проще 
data_[index] = value
чем
alloc_.construct(index, data[index])

Как правильней?

2019-12-01 10:24 UTC, smirnov-vs requested changes

2019-12-01 10:24 UTC, smirnov-vs commented on 08/vector.h
> +                new_data_[i] = (i >= size_ ? value_type() : data_[i]);
это неправильно, потому что слева в функцию передается мусор, в общем случае это ub
нужен construct

2019-12-01 10:24 UTC, smirnov-vs commented on 08/vector.h
> +        std::copy(data_, data_ + size_, other.data_);
аналогично

2019-12-01 10:24 UTC, smirnov-vs commented on 08/vector.h
> +template <class T, class Allocator = std::allocator<T>>
а где аллокатор?

2019-12-01 11:24 UTC, makarovNick commented on 08/vector.h
> +template <class T, class Allocator = std::allocator<T>>
> а где аллокатор?
А вроде сказали, что не нужен

2019-12-02 17:15 UTC, smirnov-vs commented on 08/vector.h
> +template <class T, class Allocator = std::allocator<T>>
В задании написано, что надо реализовать аллокатор

2019-12-03 08:43 UTC, smirnov-vs commented on 08/vector.h
> +template <class T, class Allocator = std::allocator<T>>
Обсудил с Максимом, он в итоге вспомнил, что его делать все таки необязательно)

2019-12-03 08:43 UTC, smirnov-vs commented on 08/vector.h
> +        emplace_back(std::forward<value_type>(__x));
форвард на rvalue ссылку

2019-12-03 13:32 UTC, makarovNick commented on 08/vector.h
> +template <class T, class Allocator = std::allocator<T>>
> Обсудил с Максимом, он в итоге вспомнил, что его делать все таки необязательно)

Он проще всего оказался.

2019-12-03 13:35 UTC, makarovNick commented on 08/vector.h
> +        emplace_back(std::forward<value_type>(__x));
> форвард на rvalue ссылку

Исправил.

2019-12-03 13:42 UTC, makarovNick commented on 08/vector.h
> +        emplace_back(std::forward<value_type>(__x));
@smirnov-vs ,
Вот у меня есть два конструктора: 
    vector(size_type __size, value_type&& defolt)
    vector(size_type __size, const_reference defolt)

И они почти дублируются. Их же можно с помощью универсальной ссылки заменить?(одним конструктором)

2019-12-05 20:32 UTC, smirnov-vs commented on 08/vector.h
> +        emplace_back(std::forward<value_type>(__x));
можно, если добавить темплейт и ограничить его через enable_if
или же сделать передачу по значению, но не забывать мувать его дальше, будет либо 2 мува, либо 1 копия и мув

2019-12-05 20:33 UTC, smirnov-vs approved these changes

2019-12-06 08:30 UTC, merged