Home task 9
makarovNick/made_2019_cpp pull request #8
Opened 2019-12-11 11:00 UTC by makarovNick

2019-12-11 22:09 UTC, smirnov-vs requested changes

2019-12-11 22:09 UTC, smirnov-vs commented on 09/threadpool.h
> +            std::bind((func),(args)...)
здесь что ли не получается?
какой код не работает?

2019-12-11 22:09 UTC, smirnov-vs commented on 09/threadpool.h
> +                            std::cerr << e.what() << std::endl;
неожиданное поведение библиотеки

2019-12-11 23:02 UTC, makarovNick commented on 09/threadpool.h
> +            std::bind((func),(args)...)
Я хочу заменить на лямбду, но тогда нельзя использовать для функтора, компилятор ругается.

2019-12-11 23:05 UTC, makarovNick commented on 09/threadpool.h
> +            tasks.emplace([task]()
Здесь я связывал [&] (){...} , и по неизвестной причине программа зависала через раз. Я потыкался везде и вот нашёл причину.

2019-12-11 23:08 UTC, makarovNick commented on 09/threadpool.h
> +                            std::cerr << e.what() << std::endl;
Не понял. 🧐

2019-12-13 10:28 UTC, smirnov-vs commented on 09/threadpool.h
> +                            std::cerr << e.what() << std::endl;
ну я вот использую тред пул, там вылетает ошибка, а вместо того чтобы мне её отдать, она почему то уходит на stderr, как быть в такой ситуации

2019-12-13 10:29 UTC, smirnov-vs commented on 09/threadpool.h
> +            tasks.emplace([task]()
скорее всего проблема была в том, что ссылка была на уничтоженный стек

2019-12-13 10:30 UTC, smirnov-vs approved these changes
я зачел

2019-12-13 11:48 UTC, merged